# Generated by Codex on 2026-04-21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0023_party"),
        ("finance", "0007_rounding_roundingrule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("allow_over_limit", models.BooleanField(default=False)),
                ("over_limit_percentage", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5)),
                ("block_sales", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_branch_records", to="core.branch")),
                ("fiscal_year", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_fiscal_year_records", to="core.fiscalyear")),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="CreditLimit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("credit_limit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("used_credit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=14)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_branch_records", to="core.branch")),
                ("fiscal_year", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_fiscal_year_records", to="core.fiscalyear")),
                ("party", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="credit_limit", to="core.party")),
                ("policy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="credit_limits", to="finance.creditpolicy")),
            ],
            options={"ordering": ["party__name", "id"]},
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_type", models.CharField(choices=[("opening", "Opening"), ("invoice", "Invoice"), ("bill", "Bill"), ("payment", "Payment"), ("credit_note", "Credit Note"), ("debit_note", "Debit Note"), ("journal", "Journal"), ("adjustment", "Adjustment")], max_length=50)),
                ("document_id", models.CharField(blank=True, max_length=50)),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("transaction_date", models.DateField(default=django.utils.timezone.localdate)),
                ("debit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("credit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("balance_after", models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ("is_system_generated", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_branch_records", to="core.branch")),
                ("content_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="finance_credit_transactions", to="contenttypes.contenttype")),
                ("fiscal_year", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_fiscal_year_records", to="core.fiscalyear")),
                ("party", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="credit_transactions", to="core.party")),
            ],
            options={"ordering": ["transaction_date", "id"]},
        ),
    ]
