SIDEBAR_ITEMS = [
    {
        "label": "Workforce",
        "icon": "users",
        "children": [
            {
                "label": "Employees",
                "icon": "user-check",
                "url_name": "employee_list",
                "match": "/core/employees",
            },
            {
                "label": "Departments",
                "icon": "layers",
                "url_name": "department_list",
                "match": "/core/departments",
            },
            {
                "label": "Designations",
                "icon": "briefcase",
                "url_name": "designation_list",
                "match": "/core/designations",
            },
            {
                "label": "Team Roles",
                "icon": "shield",
                "url_name": "team_role_list",
                "match": "/core/team-roles",
            },
            {
                "label": "Teams",
                "icon": "git-branch",
                "url_name": "team_list",
                "match": "/core/teams",
            },
            {
                "label": "Employment Types",
                "icon": "users",
                "url_name": "employeement_type_list",
                "match": "/core/employeement-types",
            },
            {
                "label": "Shifts",
                "icon": "clock",
                "url_name": "shift_list",
                "match": "/core/shifts",
            },
            {
                "label": "Shift Rotations",
                "icon": "repeat",
                "url_name": "employee_shift_list",
                "match": "/core/employee-shifts",
            }
        ],
    },
    {
        "label": "Leave",
        "icon": "calendar",
        "children": [
            {
                "label": "Leave Types",
                "icon": "calendar",
                "url_name": "leave_type_list",
                "match": "/core/leave-types",
            },
            {
                "label": "Holiday Calendars",
                "icon": "calendar-days",
                "url_name": "holiday_calendar_list",
                "match": "/core/holiday-calendars",
            },
            {
                "label": "Holiday Calendar View",
                "icon": "calendar",
                "url_name": "holiday_calendar_view",
                "match": "/hr/holiday-calendar",
            },
            {
                "label": "Leave Requests",
                "icon": "calendar-check",
                "url_name": "leave_request_list",
                "match": "/core/leave-requests",
            },
            {
                "label": "Leave Balances",
                "icon": "scale",
                "url_name": "leave_balance_list",
                "match": "/core/leave-balances",
            },
            {
                "label": "Leave Ledger",
                "icon": "file-text",
                "url_name": "leave_ledger_list",
                "match": "/core/leave-ledger",
            },
            {
                "label": "Leave Accruals",
                "icon": "trending-up",
                "url_name": "leave_accrual_list",
                "match": "/core/leave-accruals",
            },
            {
                "label": "Leave Balance Report",
                "icon": "bar-chart-2",
                "url_name": "leave_balance_summary_report",
                "match": "/hr/reports/leave-balance-summary",
            },
        ],
    },
    {
        "label": "Attendance",
        "icon": "clipboard",
        "children": [
            {
                "label": "Attendance",
                "icon": "calendar",
                "url_name": "attendance_list",
                "match": "/core/attendances",
            },
            {
                "label": "Attendance Adjustments",
                "icon": "edit-3",
                "url_name": "attendance_adjustment_list",
                "match": "/core/attendance-adjustments",
            },
            {
                "label": "Overtime Requests",
                "icon": "clock",
                "url_name": "overtime_request_list",
                "match": "/core/overtime-requests",
            },
            {
                "label": "Overtime Records",
                "icon": "file-text",
                "url_name": "overtime_record_list",
                "match": "/core/overtime-records",
            },
            {
                "label": "Attendance History Report",
                "icon": "bar-chart-2",
                "url_name": "attendance_history_report",
                "match": "/hr/reports/attendance-history",
            },
        ],
    },
    {
        "label": "Rules & Compliance",
        "icon": "shield",
        "children": [
            {
                "label": "Policies",
                "icon": "shield",
                "url_name": "policy_list",
                "match": "/core/policies",
            },
        ],
    },
    {
        "label": "Payroll",
        "icon": "dollar-sign",
        "children": [
            {
                "label": "Salary Components",
                "icon": "list",
                "url_name": "salary_component_list",
                "match": "/core/salary-components",
            },
            {
                "label": "Salary Structures",
                "icon": "layers",
                "url_name": "salary_structure_list",
                "match": "/core/salary-structures",
            },
            {
                "label": "Employee Salary",
                "icon": "user-check",
                "url_name": "employee_salary_assignment_list",
                "match": "/core/employee-salary-assignments",
            },
            {
                "label": "Payroll Runs",
                "icon": "play-circle",
                "url_name": "payroll_run_list",
                "match": "/core/payroll-runs",
            },
            {
                "label": "Processed Payroll",
                "icon": "file-text",
                "url_name": "payroll_run_employee_list",
                "match": "/core/payroll-run-employees",
            },
            {
                "label": "Payroll Components",
                "icon": "list",
                "url_name": "payroll_run_component_list",
                "match": "/core/payroll-run-components",
            },
            {
                "label": "Attendance Inputs",
                "icon": "clipboard",
                "url_name": "attendance_payroll_summary_list",
                "match": "/core/attendance-payroll-summaries",
            },
            {
                "label": "Leave Inputs",
                "icon": "calendar",
                "url_name": "leave_payroll_impact_list",
                "match": "/core/leave-payroll-impacts",
            },
            {
                "label": "Adjustments",
                "icon": "sliders",
                "url_name": "payroll_adjustment_list",
                "match": "/core/payroll-adjustments",
            },
            {
                "label": "Tax Slabs",
                "icon": "percent",
                "url_name": "tax_slab_list",
                "match": "/core/tax-slabs",
            },
            {
                "label": "Tax Declarations",
                "icon": "file-text",
                "url_name": "employee_tax_declaration_list",
                "match": "/core/employee-tax-declarations",
            },
            {
                "label": "Provident Funds",
                "icon": "shield",
                "url_name": "provident_fund_list",
                "match": "/core/provident-funds",
            },
            {
                "label": "SSF Contributions",
                "icon": "briefcase",
                "url_name": "ssf_contribution_list",
                "match": "/core/ssf-contributions",
            },
            {
                "label": "Payslips",
                "icon": "file",
                "url_name": "payslip_list",
                "match": "/core/payslips",
            },
            {
                "label": "Payroll Approvals",
                "icon": "check-circle",
                "url_name": "payroll_approval_list",
                "match": "/core/payroll-approvals",
            },
            {
                "label": "Payroll Locks",
                "icon": "lock",
                "url_name": "payroll_lock_list",
                "match": "/core/payroll-locks",
            },
            {
                "label": "Payroll Logs",
                "icon": "activity",
                "url_name": "payroll_log_list",
                "match": "/core/payroll-logs",
            },
            {
                "label": "Payroll Settings",
                "icon": "settings",
                "url_name": "payroll_setting_list",
                "match": "/core/payroll-settings",
            },
            {
                "label": "Report Layouts",
                "icon": "layout",
                "url_name": "report_layout_list",
                "match": "/core/report-layouts",
            },
            {
                "label": "Report Templates",
                "icon": "file-text",
                "url_name": "report_template_list",
                "match": "/core/report-templates",
            },
            {
                "label": "Loan Types",
                "icon": "credit-card",
                "url_name": "loan_type_list",
                "match": "/core/loan-types",
            },
            {
                "label": "Loan Applications",
                "icon": "file-plus",
                "url_name": "loan_application_list",
                "match": "/core/loan-applications",
            },
            {
                "label": "Loan Accounts",
                "icon": "briefcase",
                "url_name": "loan_account_list",
                "match": "/core/loan-accounts",
            },
            {
                "label": "Loan Installments",
                "icon": "list",
                "url_name": "loan_installment_list",
                "match": "/core/loan-installments",
            },
            {
                "label": "Loan Repayments",
                "icon": "repeat",
                "url_name": "loan_repayment_list",
                "match": "/core/loan-repayments",
            },
            {
                "label": "Loan Ledger",
                "icon": "file-text",
                "url_name": "loan_ledger_list",
                "match": "/core/loan-ledger",
            },
        ],
    },
    {
        "label": "Recruitment",
        "icon": "briefcase",
        "children": [
            {
                "label": "Job Categories",
                "icon": "tag",
                "url_name": "job_category_list",
                "match": "/core/job-categories",
            },
            {
                "label": "Job Skills",
                "icon": "tag",
                "url_name": "job_skill_list",
                "match": "/core/job-skills",
            },
            {
                "label": "Skill Levels",
                "icon": "tag",
                "url_name": "skill_level_list",
                "match": "/core/skill-levels",
            },
            {
                "label": "Job Posting Channels",
                "icon": "tag",
                "url_name": "job_posting_channel_list",
                "match": "/core/job-posting-channels",
            },
            {
                "label": "Job Positions",
                "icon": "briefcase",
                "url_name": "job_position_list",
                "match": "/core/job_position",
            },
            {
                "label": "Hiring Plans",
                "icon": "users",
                "url_name": "hiring_plan_list",
                "match": "/core/hiring-plans",
            },
            {
                "label": "Job Batches",
                "icon": "layers",
                "url_name": "job_batch_list",
                "match": "/core/job-batches",
            },
            {
                "label": "Job Requisitions",
                "icon": "layers",
                "url_name": "job_requisition_list",
                "match": "/core/job-requisitions",
            },
            {
                "label": "Job Postings",
                "icon": "briefcase",
                "url_name": "job_posting_list",
                "match": "/core/job-postings",
            },
            {
                "label": "Applicants",
                "icon": "users",
                "url_name": "applicant_list",
                "match": "/core/applicants",
            },
            {
                "label": "Applications",
                "icon": "users",
                "url_name": "job_application_list",
                "match": "/core/job-applicants",
            },
            {
                "label": "Interview Stages",
                "icon": "layers",
                "url_name": "interview_stage_list",
                "match": "/core/interview-stages",
            },
            {
                "label": "Interviews",
                "icon": "calendar",
                "url_name": "interview_list",
                "match": "/core/interviews",
            },
            {
                "label": "Job Offers",
                "icon": "file-text",
                "url_name": "job_offer_list",
                "match": "/core/job-offers",
            },
            {
                "label": "Hires",
                "icon": "user-plus",
                "url_name": "hire_list",
                "match": "/core/hires",
            },
        ],
    },
]
