from .department_data_table import DepartmentDataTableView
from .designation_data_table import DesignationDataTableView
from .employee_data_table import EmployeeDataTableView
from .hire_data_table import HireDataTableView
from .shift_data_table import ShiftDataTableView
from .leave_type_data_table import LeaveTypeDataTableView
