# Generated by Django 6.0.2 on 2026-04-09 15:52

from django.db import migrations


TASK_STATUSES = [
    {"name": "Draft", "code": "draft", "is_default": False, "badge_color": "secondary", "sequence": 0},
    {"name": "Pending", "code": "pending", "is_default": False, "badge_color": "warning", "sequence": 1},
    {"name": "Approved", "code": "approved", "is_default": False, "badge_color": "success", "sequence": 2},
    {"name": "In Progress", "code": "in_progress", "is_default": False, "badge_color": "primary", "sequence": 3},
    {"name": "On Hold", "code": "on_hold", "is_default": False, "badge_color": "warning", "sequence": 4},
    {"name": "Blocked", "code": "blocked", "is_default": False, "badge_color": "danger", "sequence": 5},
    {"name": "In Review", "code": "in_review", "is_default": False, "badge_color": "info", "sequence": 6},
    {"name": "Completed", "code": "completed", "is_default": False, "is_closed": True, "badge_color": "success", "sequence": 7},
    {"name": "Cancelled", "code": "cancelled", "is_default": False, "is_closed": True, "is_cancelled": True, "badge_color": "dark", "sequence": 8},
    {"name": "Rejected", "code": "rejected", "is_default": False, "is_closed": True, "badge_color": "danger", "sequence": 9},
    {"name": "To Do", "code": "to_do", "is_default": True, "badge_color": "secondary", "sequence": 10},
    {"name": "Done", "code": "done", "is_default": False, "is_closed": True, "badge_color": "success", "sequence": 11},
]


def seed_task_statuses(apps, schema_editor):
    TaskStatus = apps.get_model("task", "TaskStatus")
    db_alias = schema_editor.connection.alias

    for status in TASK_STATUSES:
        TaskStatus.objects.using(db_alias).update_or_create(
            code=status["code"],
            defaults={
                "name": status["name"],
                "is_default": status.get("is_default", False),
                "is_closed": status.get("is_closed", False),
                "is_cancelled": status.get("is_cancelled", False),
                "badge_color": status.get("badge_color"),
                "sequence": status["sequence"],
            },
        )


def unseed_task_statuses(apps, schema_editor):
    TaskStatus = apps.get_model("task", "TaskStatus")
    db_alias = schema_editor.connection.alias
    codes = [status["code"] for status in TASK_STATUSES]
    TaskStatus.objects.using(db_alias).filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_task_statuses, unseed_task_statuses),
    ]
