# Generated by Django 6.0.2 on 2026-05-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_task_billable_department_task_billable_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklabel',
            name='color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('purple', 'Purple'), ('orange', 'Orange'), ('teal', 'Teal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='badge_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('purple', 'Purple'), ('orange', 'Orange'), ('teal', 'Teal')], max_length=20, null=True),
        ),
    ]
