# Generated by Django 6.0.2 on 2026-05-20 00:00

from django.db import migrations


LEAD_SOURCES = [
    ("FACEBOOK_ADS", "Facebook Ads"),
    ("INSTAGRAM", "Instagram"),
    ("WALK_IN", "Walk-in"),
    ("REFERRAL", "Referral"),
    ("WEBSITE", "Website"),
    ("TIKTOK", "TikTok"),
    ("WHATSAPP", "WhatsApp"),
]


def seed_lead_sources(apps, schema_editor):
    LeadSource = apps.get_model("crm", "LeadSource")

    for code, name in LEAD_SOURCES:
        LeadSource.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "is_default": False,
                "is_active": True,
            },
        )


def unseed_lead_sources(apps, schema_editor):
    LeadSource = apps.get_model("crm", "LeadSource")
    LeadSource.objects.filter(code__in=[code for code, _name in LEAD_SOURCES]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_lead_sources, unseed_lead_sources),
    ]
