# Generated by Django 6.0.2 on 2026-05-23 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_service_types(apps, schema_editor):
    ServiceType = apps.get_model('crm', 'ServiceType')
    service_types = [
        {"name": "Physical Service", "code": "physical_service", "remarks": "Physical services.", "is_active": True},
        {"name": "Digital Service", "code": "digital_service", "remarks": "Digital services.", "is_active": True}, 
        {"name": "Consultation", "code": "consultation", "remarks": "One-on-one consultation sessions.", "is_active": True},
        {"name": "Courses", "code": "courses", "remarks": "Online courses and workshops.", "is_active": True}, 
        {"name": "Subscription", "code": "subscription", "remarks": "Subscription-based services.", "is_active": True}, 
        {"name": "Product Service", "code": "product_service", "remarks": "Product services.", "is_active": True}, 
    ]
    for service_type in service_types:
        ServiceType.objects.create(**service_type)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_partyindividualprofile'),
        ('crm', '0003_leadstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_branch_records', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_fiscal_year_records', to='core.fiscalyear')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_organization_records', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_service_types),
    ]
