# Generated by Django 6.0.2 on 2026-03-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the organization', max_length=25, null=True, unique=True)),
                ('registration_number', models.CharField(blank=True, help_text='Registration number of the organization', max_length=100, null=True, unique=True)),
                ('pan_vat_number', models.CharField(blank=True, help_text='PAN/VAT number of the organization', max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the organization', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address of the organization', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Website URL of the organization', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo of the organization', null=True, upload_to='organization_logos/')),
                ('address', models.TextField(blank=True, help_text='Address of the organization', null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Name of the contact person', max_length=100, null=True)),
                ('calendar', models.CharField(blank=True, choices=[('AD', 'AD'), ('BS', 'BS')], help_text='Calendar type', max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
