# Generated by Django 6.0.2 on 2026-03-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_approvalentity"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ApprovalEntity",
            new_name="ErpEntity",
        ),
        migrations.AlterModelTable(
            name="erpentity",
            table="erp_entity",
        ),
    ]
