# Generated by Django 6.0.2 on 2026-03-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_approvalworkflow_rule_condition"),
    ]

    operations = [
        migrations.RenameField(
            model_name="approvalworkflow",
            old_name="approval_entity",
            new_name="entity",
        ),
        migrations.AlterModelTable(
            name="approvalworkflow",
            table="approval_workflows",
        ),
    ]
