# Generated by Django 6.0.2 on 2026-03-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_approvalworkflow_entity_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflow',
            name='entity',
            field=models.ForeignKey(blank=True, db_column='entity_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.approvalentity'),
        ),
    ]
