# Generated by Django 6.0.2 on 2026-03-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_approvalworkflow_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalworkflowrule",
            name="condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="core.approvalworkflowcondition",
            ),
        ),
    ]
