# Generated by Django 6.0.2 on 2026-04-19 00:10

from django.db import migrations


PARTY_TYPES = [
    "Customer",
    "Vendor",
    "Supplier",
    "Employee",
    "Member",
    "Partner",
]


def seed_party_types(apps, schema_editor):
    PartyType = apps.get_model("core", "PartyType")
    db_alias = schema_editor.connection.alias

    for name in PARTY_TYPES:
        PartyType.objects.using(db_alias).update_or_create(
            name=name,
            defaults={
                "is_active": True,
            },
        )


def unseed_party_types(apps, schema_editor):
    PartyType = apps.get_model("core", "PartyType")
    db_alias = schema_editor.connection.alias
    PartyType.objects.using(db_alias).filter(name__in=PARTY_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_partytype"),
    ]

    operations = [
        migrations.RunPython(seed_party_types, unseed_party_types),
    ]
