# Generated by Django 6.0.2 on 2026-04-19 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def seed_party_roles(apps, schema_editor):
    PartyRole = apps.get_model("core", "PartyRole")
    db_alias = schema_editor.connection.alias

    roles = [
        {"name": "Customer", "code": "customer"},
        {"name": "Supplier", "code": "supplier"},
        {"name": "Employee", "code": "staff"},
        {"name": "Buyer", "code": "buyer"},
        {"name": "Seller", "code": "seller"},
    ]

    for role in roles:
        PartyRole.objects.using(db_alias).update_or_create(
            name=role["name"],
            defaults={
                "code": role["code"],
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_seed_party_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_branch_records', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_fiscal_year_records', to='core.fiscalyear')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_organization_records', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
