# Generated by Django 6.0.2 on 2026-04-19 16:05

from django.db import migrations


PARTY_ROLES = [
    {"name": "Customer", "code": "CUSTOMER"},
    {"name": "Vendor", "code": "VENDOR"},
    {"name": "Supplier", "code": "SUPPLIER"},
    {"name": "Employee", "code": "EMPLOYEE"},
    {"name": "Member", "code": "MEMBER"},
    {"name": "Partner", "code": "PARTNER"},
]


def seed_party_roles(apps, schema_editor):
    PartyRole = apps.get_model("core", "PartyRole")
    db_alias = schema_editor.connection.alias

    for party_role in PARTY_ROLES:
        PartyRole.objects.using(db_alias).update_or_create(
            code=party_role["code"],
            defaults={
                "name": party_role["name"],
                "is_active": True,
            },
        )


def unseed_party_roles(apps, schema_editor):
    PartyRole = apps.get_model("core", "PartyRole")
    db_alias = schema_editor.connection.alias
    PartyRole.objects.using(db_alias).filter(
        code__in=[party_role["code"] for party_role in PARTY_ROLES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_partyrole"),
    ]

    operations = [
        migrations.RunPython(seed_party_roles, unseed_party_roles),
    ]
