# Generated by Django 6.0.2 on 2026-06-12 02:20

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    """Create the default superuser if it does not already exist."""
    User = apps.get_model("auth", "User")

    if not User.objects.filter(email="admin@admin.com").exists():
        User.objects.create(
            username="admin@admin.com",
            email="admin@admin.com",
            first_name="Super",
            last_name="Admin",
            password=make_password("nep@nest123"),
            is_staff=True,
            is_superuser=True,
            is_active=True,
        )


def delete_superuser(apps, schema_editor):
    """Reverse migration — remove the default superuser."""
    User = apps.get_model("auth", "User")
    User.objects.filter(email="admin@admin.com").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_partyindividualprofile"),
    ]

    operations = [
        migrations.RunPython(
            create_superuser,
            reverse_code=delete_superuser,
        ),
    ]