from . import attendance_payroll_summary  # noqa: F401
from . import employee_salary_assignment  # noqa: F401
from . import leave_payroll_impact  # noqa: F401
from . import payroll_adjustment  # noqa: F401
from . import payroll_run  # noqa: F401
from . import payroll_run_component  # noqa: F401
from . import payroll_run_employee  # noqa: F401
from . import payroll_approval  # noqa: F401
from . import payroll_lock  # noqa: F401
from . import payroll_log  # noqa: F401
from . import payroll_setting  # noqa: F401
from . import payslip  # noqa: F401
from . import salary_component  # noqa: F401
from . import salary_structure  # noqa: F401
from . import tax_slab  # noqa: F401
from . import employee_tax_declaration  # noqa: F401
from . import provident_fund  # noqa: F401
from . import ssf_contribution  # noqa: F401
