# Generated by Codex on 2026-04-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("tax_type", models.CharField(choices=[("vat", "VAT"), ("gst", "GST"), ("service", "Service Tax"), ("withholding", "Withholding Tax"), ("excise", "Excise"), ("custom", "Custom")], default="vat", max_length=30)),
                ("calculation_method", models.CharField(choices=[("percentage", "Percentage"), ("fixed", "Fixed Amount")], default="percentage", max_length=20)),
                ("application_scope", models.CharField(choices=[("sales", "Sales"), ("purchase", "Purchase"), ("both", "Both")], default="both", max_length=20)),
                ("rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("fixed_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_inclusive", models.BooleanField(default=False)),
                ("is_recoverable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="TaxGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("application_scope", models.CharField(choices=[("sales", "Sales"), ("purchase", "Purchase"), ("both", "Both")], default="both", max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("rule_type", models.CharField(choices=[("line_net", "Line Net"), ("document_net", "Document Net"), ("shipping", "Shipping"), ("actual", "Actual Amount")], default="line_net", max_length=20)),
                ("application_scope", models.CharField(choices=[("sales", "Sales"), ("purchase", "Purchase"), ("both", "Both")], default="both", max_length=20)),
                ("min_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("max_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("priority", models.PositiveIntegerField(default=1)),
                ("stop_processing", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tax", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rules", to="finance.tax")),
            ],
            options={"ordering": ["priority", "name", "id"]},
        ),
        migrations.CreateModel(
            name="TaxGroupItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("override_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("is_compound", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tax", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tax_group_items", to="finance.tax")),
                ("tax_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="finance.taxgroup")),
            ],
            options={"ordering": ["sequence", "id"]},
        ),
        migrations.AddConstraint(
            model_name="taxgroupitem",
            constraint=models.UniqueConstraint(fields=("tax_group", "tax"), name="unique_tax_group_item_tax"),
        ),
    ]
