# Generated by Codex on 2026-04-21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_remove_journalline_credit_amount_and_more"),
        ("billing", "0002_billingdocument_billingitem"),
        ("core", "0023_party"),
        ("finance", "0005_seed_payment_methods_nepal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("reference_date", models.DateField(blank=True, null=True)),
                ("payment_type", models.CharField(choices=[("receive", "Receive"), ("pay", "Pay")], max_length=10)),
                ("exchange_rate", models.DecimalField(decimal_places=6, default=Decimal("1.000000"), max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("allocated_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=14)),
                ("unapplied_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=14)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("posted", "Posted"), ("cancelled", "Cancelled")], default="draft", max_length=20)),
                ("posted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("payment_no", models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ("billing_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="billing.billingprofile")),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_branch_records", to="core.branch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created_records", to=settings.AUTH_USER_MODEL)),
                ("currency", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="finance_payments", to="core.currency")),
                ("fiscal_year", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_fiscal_year_records", to="core.fiscalyear")),
                ("journal_entry", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payment", to="account.journalentry")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_organization_records", to="core.organization")),
                ("party", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="core.party")),
                ("payment_method", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="finance.paymentmethod")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated_records", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("remarks", models.CharField(blank=True, max_length=255)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("billing_document", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_allocations", to="billing.billingdocument")),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allocations", to="finance.payment")),
            ],
            options={"ordering": ["sequence", "id"]},
        ),
    ]
