# Generated by Codex on 2026-04-21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_party"),
        ("finance", "0006_payment_paymentallocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rounding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("application_scope", models.CharField(choices=[("sales", "Sales"), ("purchase", "Purchase"), ("both", "Both")], default="both", max_length=20)),
                ("rounding_method", models.CharField(choices=[("half_up", "Half Up"), ("half_down", "Half Down"), ("half_even", "Half Even"), ("up", "Round Up"), ("down", "Round Down"), ("ceiling", "Ceiling"), ("floor", "Floor")], default="half_up", max_length=20)),
                ("round_on", models.CharField(choices=[("line", "Line Amount"), ("document", "Document Total"), ("tax", "Tax Amount"), ("grand_total", "Grand Total"), ("payment", "Payment Amount")], default="document", max_length=20)),
                ("precision", models.PositiveSmallIntegerField(default=2)),
                ("increment", models.DecimalField(decimal_places=6, default=Decimal("0.010000"), max_digits=12)),
                ("is_cash_rounding", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_branch_records", to="core.branch")),
                ("fiscal_year", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_fiscal_year_records", to="core.fiscalyear")),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="RoundingRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("name", models.CharField(max_length=120)),
                ("application_scope", models.CharField(choices=[("sales", "Sales"), ("purchase", "Purchase"), ("both", "Both")], default="both", max_length=20)),
                ("document_type", models.CharField(choices=[("all", "All Documents"), ("invoice", "Invoice"), ("bill", "Bill"), ("credit_note", "Credit Note"), ("debit_note", "Debit Note"), ("payment", "Payment")], default="all", max_length=20)),
                ("min_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("max_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("priority", models.PositiveIntegerField(default=1)),
                ("stop_processing", models.BooleanField(default=False)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_branch_records", to="core.branch")),
                ("currency", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="rounding_rules", to="core.currency")),
                ("fiscal_year", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_fiscal_year_records", to="core.fiscalyear")),
                ("party_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="rounding_rules", to="core.partytype")),
                ("payment_method", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="rounding_rules", to="finance.paymentmethod")),
                ("rounding", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rules", to="finance.rounding")),
            ],
            options={"ordering": ["priority", "name", "id"]},
        ),
    ]

