# Generated by Django 6.0.2 on 2026-03-21 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_jobrequisitionapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequisitionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(blank=True, max_length=250, null=True)),
                ('position_description', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='hr.designation')),
                ('job_requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='hr.jobrequisition')),
            ],
            options={
                'ordering': ['position_title'],
            },
        ),
    ]
