# Generated by Django 6.0.2 on 2026-03-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0040_alter_employeeshift_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_carry_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_encashable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_days_per_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_attachment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
