# Generated by Django 6.0.2 on 2026-04-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_assetassignment_expected_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetstatus',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assetstatus',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
