# Generated by Django 6.0.2 on 2026-04-06 15:14

from django.db import migrations



def seed_asset_incident_types(app, schema_editor):
    AssetIncidentType = app.get_model("assets", "AssetIncidentType")
    incident_types = [
        {"name": "Equipment Damage", "code": "EQ_DAMAGE", "require_approval": True, "auto_create_maintenance": True, "financial_impact": True},
        {"name": "Theft", "code": "THEFT", "require_approval": True, "auto_create_maintenance": False, "financial_impact": True},
        {"name": "Vandalism", "code": "VANDALISM", "require_approval": True, "auto_create_maintenance": False, "financial_impact": True},
        {"name": "Damage", "code": "DAMAGE", "require_approval": True, "auto_create_maintenance": False, "financial_impact": True},
        {"name": "Lost", "code": "LOST", "require_approval": True, "auto_create_maintenance": False, "financial_impact": True},
        {"name": "Expired License", "code": "EXPIRED_LICENSE", "require_approval": True, "auto_create_maintenance": False, "financial_impact": True},
        {"name": "Inspection Failure", "code": "INSPECTION_FAILURE", "require_approval": True, "auto_create_maintenance": False, "financial_impact": True}
    ]

    for incident_type in incident_types:
        AssetIncidentType.objects.update_or_create(
            code=incident_type["code"],
            defaults=incident_type
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_assetincidenttype'),
    ]

    operations = [
        migrations.RunPython(seed_asset_incident_types),
    ]
