# Generated by Django 6.0.2 on 2026-04-06 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_seed_asset_incident_ttypes'),
        ('core', '0018_locationtype_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approval_deduction_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reported', 'Reported'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='draft', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_incidents', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incidents', to='assets.asset')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asset_incidents', to='core.branch')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_incidents', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asset_incidents', to='core.fiscalyear')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asset_incidents', to='assets.assetincidenttype')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_asset_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-incident_date', '-id'],
            },
        ),
    ]
