# Generated by Django 6.0.2 on 2026-04-09 16:30

from django.db import migrations


TASK_TYPES = [
    {"name": "General Task", "code": "general", "sequence": 0},
    {"name": "Bug", "code": "bug", "sequence": 1},
    {"name": "Feature", "code": "feature", "sequence": 2},
    {"name": "Improvement", "code": "improvement", "sequence": 3},
    {"name": "Research", "code": "research", "sequence": 4},
    {"name": "Support", "code": "support", "sequence": 5},
    {"name": "Maintenance", "code": "maintenance", "sequence": 6},
]


def seed_task_types(apps, schema_editor):
    TaskType = apps.get_model("task", "TaskType")
    db_alias = schema_editor.connection.alias

    for task_type in TASK_TYPES:
        TaskType.objects.using(db_alias).update_or_create(
            code=task_type["code"],
            defaults={
                "name": task_type["name"],
                "sequence": task_type["sequence"],
                "is_active": True,
            },
        )


def unseed_task_types(apps, schema_editor):
    TaskType = apps.get_model("task", "TaskType")
    db_alias = schema_editor.connection.alias
    codes = [task_type["code"] for task_type in TASK_TYPES]
    TaskType.objects.using(db_alias).filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_tasktype"),
    ]

    operations = [
        migrations.RunPython(seed_task_types, unseed_task_types),
    ]
