# Generated by Django 6.0.2 on 2026-04-11 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_locationtype_location'),
        ('task', '0011_taskmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmember',
            options={'ordering': ['task__title', 'user__username', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='taskmember',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='taskmember',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('watcher', 'Watcher')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='taskmember',
            constraint=models.UniqueConstraint(fields=('task', 'user', 'role'), name='unique_task_member_role'),
        ),
    ]
