# Generated by Codex on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0012_alter_taskmember_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="billing_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="task",
            name="billing_company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="billing_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="task",
            name="billing_status",
            field=models.CharField(
                choices=[
                    ("not_billable", "Not Billable"),
                    ("unbilled", "Unbilled"),
                    ("billed", "Billed"),
                    ("paid", "Paid"),
                ],
                default="not_billable",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="billing_type",
            field=models.CharField(
                choices=[("fixed_rate", "Fixed Fee"), ("hourly_rate", "Hourly")],
                default="fixed_rate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="invoice_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="task",
            name="is_billable",
            field=models.BooleanField(default=False),
        ),
    ]
