# Generated by Django 6.0.2 on 2026-04-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamrogym', '0005_member_status_fitness_goal_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='fitness_goal',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='fitness_goals',
            field=models.ManyToManyField(blank=True, related_name='member_profiles', to='hamrogym.fitnessgoal'),
        ),
    ]
