# Generated by Django 6.0.2 on 2026-04-29 16:26

from django.db import migrations

def seed_activity_levels(apps, schema_editor):
    ActivityLevel = apps.get_model('hamrogym', 'ActivityLevel')
    activity_levels = [
        {"name": "beginner", "is_active": True, "remarks": "Little or no exercise"},
        {"name": "intermediate", "is_active": True, "remarks": "Light exercise/sports 1-3 days/week"},
        {"name": "advanced", "is_active": True, "remarks": "Moderate exercise/sports 3-5 days/week"},
    ]
    for level in activity_levels:
        ActivityLevel.objects.update_or_create(name=level["name"], defaults=level)


def unseed_activity_levels(apps, schema_editor):
    ActivityLevel = apps.get_model('hamrogym', 'ActivityLevel')
    ActivityLevel.objects.filter(name__in=["beginner", "intermediate", "advanced"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('hamrogym', '0009_activitylevel_alter_accesstype_branch_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_activity_levels, unseed_activity_levels), 
    ]
