# Generated by Django 6.0.2 on 2026-04-29 16:43

from django.db import migrations, models

def seed_member_tag(apps, schema_editor):
    MemberTag = apps.get_model('hamrogym', 'MemberTag')
    member_tags = [
        {"name": "VIP", "is_active": True, "remarks": "Very Important Person"},
        {"name": "Regular", "is_active": True, "remarks": "Regular Member"},
        {"name": "Guest", "is_active": True, "remarks": "Guest Member"},
        {"name": "Weight Loss", "is_active": True, "remarks": "Weight Loss Member"},
        {"name": "Muscle Gain", "is_active": True, "remarks": "Muscle Gain Member"},
        {"name": "Endurance", "is_active": True, "remarks": "Endurance Member"},
        {"name": "Evening Batch", "is_active": True, "remarks": "Flexibility Member"},
        {"name": "Morning Batch", "is_active": True, "remarks": "Flexibility Member"},
        {"name": "Rehab", "is_active": True, "remarks": "Rehabilitation Member"}
    ]
    for tag in member_tags:
        MemberTag.objects.update_or_create(name=tag["name"], defaults=tag)


# def unseed_member_tag(apps, schema_editor):
#     MemberTag = apps.get_model('hamrogym', 'MemberTag')
#     MemberTag.objects.filter(name__in=[
#         "VIP", "Regular", "Guest", "Weight Loss", "Muscle Gain",
#         "Endurance", "Evening Batch", "Morning Batch", "Rehab"
#     ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('hamrogym', '0010_auto_20260429_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),

        migrations.RunPython(seed_member_tag),
    ]
