# Generated by Django 6.0.2 on 2026-05-01 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_partyindividualprofile'),
        ('hamrogym', '0013_member_activity_level_member_bmi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipextension',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RenameField(
            model_name='membermembership',
            old_name='allowed_sessions',
            new_name='total_sessions',
        ),
        migrations.RenameField(
            model_name='membershipextension',
            old_name='total_days',
            new_name='extra_days',
        ),
        migrations.RemoveField(
            model_name='membershipextension',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='membershipextension',
            name='start_date',
        ),
        migrations.AddField(
            model_name='membermembership',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membermembership',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('online', 'Online'), ('renewal', 'Renewal'), ('upgrade', 'Upgrade')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='membermembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershipextension',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_extensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MembershipRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('restriction_type', models.CharField(choices=[('time', 'Time'), ('day', 'Day'), ('usage', 'Usage')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_branch_records', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_fiscal_year_records', to='core.fiscalyear')),
                ('membership_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='hamrogym.membershipplan')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_organization_records', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['restriction_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MembershipUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upgrade_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_branch_records', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_fiscal_year_records', to='core.fiscalyear')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_upgrades', to='hamrogym.member')),
                ('new_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upgrades_to', to='hamrogym.membermembership')),
                ('old_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upgrades_from', to='hamrogym.membermembership')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_organization_records', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upgrade_date', '-id'],
            },
        ),
    ]
