# Generated by Django 6.0.2 on 2026-05-03 16:47

from django.db import migrations, models


EQUIPMENT_TYPE_DATA = [
    {"name": "Treadmill", "is_active": True, "remarks": "Cardio equipment"},
    {"name": "Dumbbell", "is_active": True, "remarks": "Free weights"},
    {"name": "Bench Press", "is_active": True, "remarks": "Strength training equipment"},
    {"name": "Bodyweight", "is_active": True, "remarks": "Bodyweight exercises"},
    {"name": "Machine", "is_active": True, "remarks": "Machine-based exercises"},
    {"name": "Cable", "is_active": True, "remarks": "Cable-based exercises"}
]

def seed_equipment_type(apps, schema_editor):
    EquipmentType = apps.get_model('hamrogym', 'EquipmentType')
    for equipment in EQUIPMENT_TYPE_DATA:
        EquipmentType.objects.create(**equipment)

class Migration(migrations.Migration):

    dependencies = [
        ('hamrogym', '0017_musclegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_equipment_type, migrations.RunPython.noop),
        
    ]
