# Generated by Django 6.0.2 on 2026-05-10 02:13

from django.db import migrations


def seed_gym_classes(apps, schema_editor):
    GymClassType = apps.get_model("hamrogym", "GymClassType")

    gym_classes = [
        {
            "name": "Yoga",
            "remarks": "A relaxing class focusing on flexibility and mindfulness.",
        },
        {
            "name": "Pilates",
            "remarks": "A core-strengthening class that improves posture and balance.",
        },
        {
            "name": "Spinning",
            "remarks": "A high-intensity cycling class that boosts cardiovascular fitness.",
        },
        {
            "name": "Zumba",
            "remarks": "A fun dance-based class that combines Latin and international music.",
        },
        {
            "name": "CrossFit",
            "remarks": "A high-intensity functional training class that builds strength and endurance.",
        },
    ]

    for gym_class in gym_classes:
        GymClassType.objects.get_or_create(
            name=gym_class["name"],
            defaults={
                "remarks": gym_class["remarks"],
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ("hamrogym", "0023_gymclass"),
    ]

    operations = [
        migrations.RunPython(seed_gym_classes),
    ]
