# Generated by Django 6.0.2 on 2026-05-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamrogym', '0025_rename_gymclass_to_gymclasstype'),
    ]

    operations = []
