# Generated by Django 6.0.2 on 2026-05-11 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def seed_class_rooms(apps, schema_editor):
    ClassRoom = apps.get_model("hamrogym", "ClassRoom")

    rooms = [
        {"name": "Yoga Hall", "capacity": 25},
        {"name": "HIIT Zone", "capacity": 20},
        {"name": "Dance Studio", "capacity": 30},
        {"name": "Spinning Room", "capacity": 18},
        {"name": "CrossFit Box", "capacity": 22},
        {"name": "Functional Area", "capacity": 20},
        {"name": "Cardio Studio", "capacity": 15},
        {"name": "Martial Arts Room", "capacity": 25},
        {"name": "Group Fitness Studio", "capacity": 35},
        {"name": "Pilates Studio", "capacity": 15},
        {"name": "Meditation Room", "capacity": 12},
        {"name": "Aerobics Hall", "capacity": 30},
        {"name": "Strength Studio", "capacity": 20},
        {"name": "Indoor Cycling Studio", "capacity": 24},
        {"name": "Recovery Room", "capacity": 10},
        {"name": "Personal Training Room", "capacity": 5},
        {"name": "Kids Activity Room", "capacity": 15},
        {"name": "Open Training Floor", "capacity": 40},
    ]

    for room in rooms:
        ClassRoom.objects.get_or_create(
            name=room["name"],
            defaults={
                "capacity": room["capacity"],
                "is_active": True,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_partyindividualprofile"),
        ('hamrogym', '0026_alter_gymclasstype_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_branch_records", to="core.branch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created_records", to=settings.AUTH_USER_MODEL)),
                ("fiscal_year", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_fiscal_year_records", to="core.fiscalyear")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="%(app_label)s_%(class)s_organization_records", to="core.organization")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated_records", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(seed_class_rooms, migrations.RunPython.noop),
    ]
