# Generated by Django 6.0.2 on 2026-05-12 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


GYM_CLASS_TABLE_SQL = """
CREATE TABLE `hamrogym_gymclass` (
    `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `created_at` datetime(6) NOT NULL,
    `updated_at` datetime(6) NOT NULL,
    `is_active` bool NOT NULL,
    `remarks` longtext NOT NULL,
    `name` varchar(200) NOT NULL,
    `difficulty_level` varchar(20) NOT NULL,
    `max_capacity` integer UNSIGNED NOT NULL CHECK (`max_capacity` >= 0),
    `duration_minutes` integer UNSIGNED NOT NULL CHECK (`duration_minutes` >= 0),
    `branch_id` bigint NULL,
    `class_type_id` bigint NULL,
    `created_by_id` integer NULL,
    `fiscal_year_id` bigint NULL,
    `organization_id` bigint NULL,
    `trainer_id` bigint NULL,
    `updated_by_id` integer NULL
)
"""

GYM_CLASS_FOREIGN_KEYS = [
    (
        "hg_gymclass_branch_fk",
        "ALTER TABLE `hamrogym_gymclass` ADD CONSTRAINT "
        "`hg_gymclass_branch_fk` "
        "FOREIGN KEY (`branch_id`) REFERENCES `core_branch` (`id`)",
    ),
    (
        "hg_gymclass_class_type_fk",
        "ALTER TABLE `hamrogym_gymclass` ADD CONSTRAINT "
        "`hg_gymclass_class_type_fk` "
        "FOREIGN KEY (`class_type_id`) REFERENCES `hamrogym_gymclasstype` (`id`)",
    ),
    (
        "hg_gymclass_created_by_fk",
        "ALTER TABLE `hamrogym_gymclass` ADD CONSTRAINT "
        "`hg_gymclass_created_by_fk` "
        "FOREIGN KEY (`created_by_id`) REFERENCES `auth_user` (`id`)",
    ),
    (
        "hg_gymclass_fiscal_year_fk",
        "ALTER TABLE `hamrogym_gymclass` ADD CONSTRAINT "
        "`hg_gymclass_fiscal_year_fk` "
        "FOREIGN KEY (`fiscal_year_id`) REFERENCES `core_fiscalyear` (`id`)",
    ),
    (
        "hg_gymclass_organization_fk",
        "ALTER TABLE `hamrogym_gymclass` ADD CONSTRAINT "
        "`hg_gymclass_organization_fk` "
        "FOREIGN KEY (`organization_id`) REFERENCES `core_organization` (`id`)",
    ),
    (
        "hg_gymclass_trainer_fk",
        "ALTER TABLE `hamrogym_gymclass` ADD CONSTRAINT "
        "`hg_gymclass_trainer_fk` "
        "FOREIGN KEY (`trainer_id`) REFERENCES `hamrogym_trainer` (`id`)",
    ),
    (
        "hg_gymclass_updated_by_fk",
        "ALTER TABLE `hamrogym_gymclass` ADD CONSTRAINT "
        "`hg_gymclass_updated_by_fk` "
        "FOREIGN KEY (`updated_by_id`) REFERENCES `auth_user` (`id`)",
    ),
]


def ensure_gym_class_table(apps, schema_editor):
    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())

    with connection.cursor() as cursor:
        if "hamrogym_gymclass" not in existing_tables:
            cursor.execute(GYM_CLASS_TABLE_SQL)

        for constraint_name, sql in GYM_CLASS_FOREIGN_KEYS:
            cursor.execute(
                """
                SELECT 1
                FROM information_schema.TABLE_CONSTRAINTS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = 'hamrogym_gymclass'
                  AND CONSTRAINT_NAME = %s
                  AND CONSTRAINT_TYPE = 'FOREIGN KEY'
                """,
                [constraint_name],
            )
            if cursor.fetchone() is None:
                cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_partyindividualprofile'),
        ('hamrogym', '0027_seed_class_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymclasstype',
            options={'ordering': ['name']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_gym_class_table, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='GymClass',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('remarks', models.TextField(blank=True)),
                        ('name', models.CharField(max_length=200)),
                        ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='Beginner', max_length=20)),
                        ('max_capacity', models.PositiveIntegerField()),
                        ('duration_minutes', models.PositiveIntegerField()),
                        ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_branch_records', to='core.branch')),
                        ('class_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_classes', to='hamrogym.gymclasstype')),
                        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                        ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_fiscal_year_records', to='core.fiscalyear')),
                        ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_organization_records', to='core.organization')),
                        ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_classes', to='hamrogym.trainer')),
                        ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['name'],
                    },
                ),
            ],
        ),
    ]
