# Generated by Django 6.0.2 on 2026-05-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hamrogym", "0028_alter_gymclasstype_options_gymclass"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="gymclasstype",
            table="gym_class_type",
        ),
    ]
