# Generated by Django 6.0.2 on 2026-03-14 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_employeeprofile_blood_group_applicant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_posting',
            new_name='JobPosting',
        ),
        migrations.AddField(
            model_name='applicant',
            name='job_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.jobposting'),
        ),
        migrations.AlterModelTable(
            name='jobposting',
            table='hr_job_posting',
        ),
    ]
