# Generated by Django 6.0.2 on 2026-03-18 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_approval_process_engine'),
        ('hr', '0012_leavetype_rename_leave_type_approvalworkflowlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringplan',
            name='fiscal_year',
            field=models.ForeignKey(help_text='Fiscal year', on_delete=django.db.models.deletion.CASCADE, to='core.fiscalyear'),
        ),
    ]
