# Generated by Django 6.0.2 on 2026-03-19 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fiscalyear_is_current'),
        ('hr', '0014_jobbatches'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_head_count', models.PositiveIntegerField(default=1)),
                ('planned_month', models.PositiveIntegerField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_plan_items', to='core.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_plan_items', to='hr.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_plan_items', to='hr.designation')),
                ('employeement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_plan_items', to='hr.employmenttype')),
                ('hiring_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hr.hiringplan')),
            ],
            options={
                'unique_together': {('hiring_plan', 'branch', 'department', 'designation', 'employeement_type')},
            },
        ),
    ]
