# Generated by Django 6.0.2 on 2026-03-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fiscalyear_is_current'),
        ('hr', '0020_jobskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='fiscal_year',
            field=models.ForeignKey(default=None, null=True, blank=True, help_text='Fiscal year', on_delete=django.db.models.deletion.CASCADE, to='core.fiscalyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrequisitionapproval',
            name='fiscal_year',
            field=models.ForeignKey(default=None, null=True, blank=True, help_text='Fiscal year', on_delete=django.db.models.deletion.CASCADE, to='core.fiscalyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrequisitionposition',
            name='fiscal_year',
            field=models.ForeignKey(default=None, null=True, blank=True, help_text='Fiscal year', on_delete=django.db.models.deletion.CASCADE, to='core.fiscalyear'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JobPositionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hr.jobrequisitionposition')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='hr.jobskill')),
            ],
            options={
                'unique_together': {('job_position', 'skill')},
            },
        ),
    ]
