# Generated by Django 6.0.2 on 2026-03-21 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fiscalyear_is_current'),
        ('hr', '0021_skilllevel_jobrequisition_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpositionskill',
            name='skill_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_position_skills', to='hr.skilllevel'),
        ),
        migrations.AlterField(
            model_name='hiringplan',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fiscalyear'),
        ),
    ]
