# Generated by Django 6.0.2 on 2026-03-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_jobapplication_source_alter_jobapplication_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('text', 'Text'), ('yes_no', 'Yes/No')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_questions', to='hr.jobposition')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
