# Generated by Django 6.0.2 on 2026-03-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fiscalyear_is_current'),
        ('hr', '0029_interview_interviewfeedback_interviewpanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateField()),
                ('salary_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(blank=True, help_text='Fiscal year', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fiscalyear')),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.jobapplication')),
            ],
            options={
                'verbose_name': 'Job Offer',
                'verbose_name_plural': 'Job Offers',
                'db_table': 'hr_job_offer',
                'ordering': ['job_application'],
            },
        ),
        migrations.CreateModel(
            name='JobOfferAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='job_offer/job_offer_attachments/')),
                ('document_type', models.CharField(blank=True, help_text='Type of the document (e.g., offer letter, contract)', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hr.joboffer')),
            ],
            options={
                'verbose_name': 'Job Offer Attachment',
                'verbose_name_plural': 'Job Offer Attachments',
                'db_table': 'hr_job_offer_attachment',
            },
        ),
    ]
