# Generated by Django 6.0.2 on 2026-03-23 15:45

import Apps.hr.models.job_offer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0030_joboffer_jobofferattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobofferattachment",
            name="file",
            field=models.FileField(
                upload_to=Apps.hr.models.job_offer.job_offer_attachment_file_path,
                validators=[Apps.hr.models.job_offer.validate_job_offer_attachment],
            ),
        ),
    ]
