# Generated by Django 6.0.2 on 2026-03-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0031_alter_jobofferattachment_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hire_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        db_column="candidate_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hires",
                        to="hr.applicant",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_column="department_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hires",
                        to="hr.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        db_column="designation_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hires",
                        to="hr.designation",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="employee_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hires",
                        to="hr.employee",
                    ),
                ),
                (
                    "job_offer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hire",
                        to="hr.joboffer",
                    ),
                ),
            ],
            options={
                "db_table": "hr_hire",
                "ordering": ["-hire_date", "-id"],
            },
        ),
    ]
