# Generated by Django 6.0.2 on 2026-03-24 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0033_attendance_attendanceadjustment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                db_column="employee_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="hr.employee",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceadjustment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
