# Generated by Django 6.0.2 on 2026-03-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0034_alter_attendance_and_adjustment_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceadjustment',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
