# Generated by Django 6.0.2 on 2026-03-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0038_overtime_request_overtimerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeshift",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_rotations",
                to="hr.employee",
            ),
        ),
    ]
