# Generated by Django 6.0.2 on 2026-03-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0041_leavetype_color_leavetype_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_allowed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accrual_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('accrual_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carry_forward_limit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carry_forward_expiry_days', models.IntegerField(default=0)),
                ('max_consecutive_days', models.IntegerField(blank=True, null=True)),
                ('min_service_days', models.IntegerField(default=0)),
                ('allow_half_day', models.BooleanField(default=True)),
                ('allow_negative_balance', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='hr.employmenttype')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='hr.leavetype')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('leave_type', 'employment_type'), name='unique_leave_policy')],
            },
        ),
    ]
