# Generated by Django 6.0.2 on 2026-03-27 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0048_payrollrun_payrollrunemployee_payrollruncomponent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePayrollImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('is_paid', models.BooleanField(default=True)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='leave_payroll_impacts', to='hr.employee')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_impacts', to='hr.leaverequest')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_impacts', to='hr.leavetype')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_impacts', to='hr.payrollrun')),
            ],
            options={
                'ordering': ['employee__employee_id', 'leave_type__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('arrear', 'Arrear'), ('bonus', 'Bonus'), ('correction', 'Correction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='hr.payrollrun')),
                ('salary_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='hr.salarycomponent')),
            ],
            options={
                'ordering': ['employee__employee_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePayrollSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('absent_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('half_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('payable_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('late_instances', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_payroll_summaries', to='hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='hr.payrollrun')),
            ],
            options={
                'ordering': ['employee__employee_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('payroll_run', 'employee'), name='unique_attendance_payroll_summary_run_employee')],
            },
        ),
    ]
