# Generated by Django 6.0.2 on 2026-03-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0049_leavepayrollimpact_payrolladjustment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('interest_type', models.CharField(choices=[('flat', 'Flat'), ('reducing', 'Reducing'), ('none', 'No Interest')], max_length=20)),
                ('default_interest_rate', models.DecimalField(decimal_places=2, help_text='Default interest rate (%)', max_digits=5)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, help_text='Maximum allowed loan amount', max_digits=12)),
                ('max_tenure_months', models.IntegerField()),
                ('min_tenure_months', models.IntegerField(default=1)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_guarantor', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_eligible_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_installment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_tenure_months', models.IntegerField()),
                ('min_tenure_months', models.IntegerField(default=1)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Override LoanType interest rate', max_digits=5, null=True)),
                ('grace_period_days', models.IntegerField(default=0)),
                ('min_credit_score', models.IntegerField(blank=True, null=True)),
                ('max_loan_percentage_of_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_emi_percentage_of_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_policies', to='hr.employmenttype')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='hr.loantype')),
            ],
            options={
                'ordering': ['priority', 'employment_type__name', 'id'],
                'unique_together': {('loan_type', 'employment_type')},
            },
        ),
    ]
