# Generated by Codex on 2026-03-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_fiscalyear_is_current"),
        ("hr", "0051_loanaccount_loanadjustment_loanapplication_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeTaxDeclaration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("declared_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("investment_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("insurance_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("other_deductions", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee", models.ForeignKey(db_column="employee_id", on_delete=django.db.models.deletion.CASCADE, related_name="tax_declarations", to="hr.employee")),
                ("fiscal_year", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="employee_tax_declarations", to="core.fiscalyear")),
            ],
            options={
                "ordering": ["employee__employee_id", "-fiscal_year__start_date", "-id"],
                "constraints": [
                    models.UniqueConstraint(fields=("employee", "fiscal_year"), name="unique_employee_tax_declaration_fiscal_year")
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("approval_level", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("remarks", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payroll_approvals", to=settings.AUTH_USER_MODEL)),
                ("payroll_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="hr.payrollrun")),
            ],
            options={
                "ordering": ["payroll_run__payroll_year", "payroll_run__payroll_month", "approval_level", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("payroll_run", "approval_level"), name="unique_payroll_approval_level_per_run")
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollLock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("locked_at", models.DateTimeField()),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payroll_locks", to=settings.AUTH_USER_MODEL)),
                ("payroll_run", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="lock_record", to="hr.payrollrun")),
            ],
            options={"ordering": ["-locked_at", "-id"]},
        ),
        migrations.CreateModel(
            name="PayrollLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("created", "Created"), ("updated", "Updated"), ("processed", "Processed"), ("approved", "Approved"), ("locked", "Locked"), ("reset", "Reset")], max_length=20)),
                ("old_data", models.JSONField(blank=True, null=True)),
                ("new_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payroll_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="hr.payrollrun")),
                ("performed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payroll_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="PayrollSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("default_working_days", models.PositiveSmallIntegerField(default=30)),
                ("overtime_calculation_method", models.CharField(choices=[("fixed_rate", "Fixed Rate"), ("hourly_rate", "Hourly Rate"), ("multiplier", "Multiplier")], default="hourly_rate", max_length=30)),
                ("rounding_method", models.CharField(choices=[("round_2", "Round 2 Decimals"), ("round_0", "Round Whole Number"), ("ceil", "Ceil"), ("floor", "Floor")], default="round_2", max_length=20)),
                ("adjustment_reference_type", models.CharField(choices=[("manual", "Manual"), ("system", "System"), ("loan", "Loan"), ("incentive", "Incentive")], default="manual", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payroll_settings", to="core.branch")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payroll_settings", to="core.organization")),
            ],
            options={
                "ordering": ["organization__name", "branch__name", "-id"],
                "constraints": [
                    models.UniqueConstraint(fields=("organization", "branch"), name="unique_payroll_setting_scope")
                ],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payslip_number", models.CharField(max_length=50, unique=True)),
                ("generated_date", models.DateField()),
                ("file_path", models.CharField(blank=True, max_length=255)),
                ("email_sent", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payroll_run_employee", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="payslip", to="hr.payrollrunemployee")),
            ],
            options={"ordering": ["-generated_date", "-id"]},
        ),
        migrations.CreateModel(
            name="ProvidentFund",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("employer_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee", models.ForeignKey(db_column="employee_id", on_delete=django.db.models.deletion.CASCADE, related_name="provident_funds", to="hr.employee")),
            ],
            options={"ordering": ["employee__employee_id", "-effective_from", "-id"]},
        ),
        migrations.CreateModel(
            name="SSFContribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("employer_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee", models.ForeignKey(db_column="employee_id", on_delete=django.db.models.deletion.CASCADE, related_name="ssf_contributions", to="hr.employee")),
            ],
            options={"ordering": ["employee__employee_id", "-effective_from", "-id"]},
        ),
        migrations.CreateModel(
            name="TaxSlab",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("min_income", models.DecimalField(decimal_places=2, max_digits=14)),
                ("max_income", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rebate_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fiscal_year", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_tax_slabs", to="core.fiscalyear")),
            ],
            options={
                "ordering": ["fiscal_year__start_date", "min_income", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("fiscal_year", "min_income"), name="unique_tax_slab_fiscal_year_min_income")
                ],
            },
        ),
    ]
