# Generated by Codex on 2026-03-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0052_payroll_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollsetting",
            name="provident_fund_employee_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_settings_pf_employee_component",
                to="hr.salarycomponent",
            ),
        ),
        migrations.AddField(
            model_name="payrollsetting",
            name="provident_fund_employer_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_settings_pf_employer_component",
                to="hr.salarycomponent",
            ),
        ),
        migrations.AddField(
            model_name="payrollsetting",
            name="ssf_employee_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_settings_ssf_employee_component",
                to="hr.salarycomponent",
            ),
        ),
        migrations.AddField(
            model_name="payrollsetting",
            name="ssf_employer_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_settings_ssf_employer_component",
                to="hr.salarycomponent",
            ),
        ),
        migrations.AddField(
            model_name="payrollsetting",
            name="tax_deduction_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_settings_tax_component",
                to="hr.salarycomponent",
            ),
        ),
    ]
