# Generated by Codex on 2026-03-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_fiscalyear_is_current"),
        ("hr", "0053_payroll_setting_component_mappings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportLayout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "html_wrapper",
                    models.TextField(
                        help_text="Shared HTML shell. Use {{ report_styles }}, {{ report_header }}, {{ report_body }}, and {{ report_footer }} placeholders."
                    ),
                ),
                ("css_content", models.TextField(blank=True)),
                ("header_html", models.TextField(blank=True)),
                ("footer_html", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_layouts",
                        to="core.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_layouts",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "code"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "report_key",
                    models.CharField(
                        help_text="Logical report identifier like payslip, salary_register, attendance_summary, or member_invoice.",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "body_html",
                    models.TextField(
                        help_text="Template body HTML. You can use Django-style variables such as {{ employee_name }} or {{ company_name }}."
                    ),
                ),
                ("css_content", models.TextField(blank=True)),
                ("header_html", models.TextField(blank=True)),
                ("footer_html", models.TextField(blank=True)),
                ("sample_context", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_templates",
                        to="core.branch",
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_templates",
                        to="hr.reportlayout",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_templates",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["report_key", "name", "code"],
            },
        ),
        migrations.AddConstraint(
            model_name="reportlayout",
            constraint=models.UniqueConstraint(
                fields=("organization", "branch", "name"),
                name="unique_report_layout_scope_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "branch", "report_key", "name"),
                name="unique_report_template_scope_key_name",
            ),
        ),
    ]
