# Generated by Django 6.0.2 on 2026-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0054_report_layout_report_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrun',
            name='payroll_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
    ]
