from . import asset_category  # noqa: F401
from . import asset_assignment  # noqa: F401
from . import asset_condition  # noqa: F401
from . import asset_location  # noqa: F401
from . import asset_maintenance  # noqa: F401
from . import depreciation_register  # noqa: F401
from . import asset_status  # noqa: F401
from . import asset_transfer  # noqa: F401
from . import asset_vendor  # noqa: F401
from . import asset  # noqa: F401
from . import asset_type  # noqa: F401
from . import asset_incident_type  # noqa: F401
from . import asset_incident  # noqa: F401
