# Generated by Django 6.0.2 on 2026-04-15 02:21

import django.db.models.deletion
from django.db import migrations, models


def backfill_is_ledger(apps, schema_editor):
    ChartOfAccount = apps.get_model("account", "ChartOfAccount")
    ChartOfAccount.objects.filter(allow_direct_posting=True).update(is_ledger=True)


def reverse_backfill_is_ledger(apps, schema_editor):
    ChartOfAccount = apps.get_model("account", "ChartOfAccount")
    ChartOfAccount.objects.update(is_ledger=False)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='is_ledger',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_no', models.CharField(blank=True, max_length=50)),
                ('vat_no', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('mobile_no', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_profile', to='account.chartofaccount')),
            ],
            options={
                'ordering': ['chart_account__code', 'id'],
            },
        ),
        migrations.RunPython(backfill_is_ledger, reverse_backfill_is_ledger),
    ]
