# Generated by Django 6.0.2 on 2026-04-09 17:20

from django.db import migrations


TASK_MODULES = [
    {"name": "Development"},
    {"name": "HR"},
    {"name": "Cleaning"},
    {"name": "Maintenance"},
    {"name": "Finance"},
    {"name": "Sales"},
]


def seed_task_modules(apps, schema_editor):
    TaskModule = apps.get_model("task", "TaskModule")
    db_alias = schema_editor.connection.alias

    for task_module in TASK_MODULES:
        TaskModule.objects.using(db_alias).update_or_create(
            name=task_module["name"],
            defaults={
                "is_active": True,
            },
        )


def unseed_task_modules(apps, schema_editor):
    TaskModule = apps.get_model("task", "TaskModule")
    db_alias = schema_editor.connection.alias
    names = [task_module["name"] for task_module in TASK_MODULES]
    TaskModule.objects.using(db_alias).filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0006_alter_tasklabel_color_taskmodule"),
    ]

    operations = [
        migrations.RunPython(seed_task_modules, unseed_task_modules),
    ]
