# Generated by Django 6.0.2 on 2026-04-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_assetassignment_assetmaintenancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
