# Generated by Django 6.0.2 on 2026-04-05 16:39

from django.db import migrations


def seed_asset_statuses(apps, schema_editor):
    AssetStatus = apps.get_model("assets", "AssetStatus")

    statuses = [
        ("Available", "AVAILABLE", False),
        ("Assigned", "ASSIGNED", False),
        ("Maintenance", "MAINTENANCE", False),
        ("Reserved", "RESERVED", False),
        ("In Transfer", "IN_TRANSFER", False),
        ("Idle", "IDLE", False),
        ("Lost", "LOST", False),
        ("Damaged", "DAMAGED", False),
        ("Disposed", "DISPOSED", True),
    ]

    for (
        name,
        code,
        is_final,
    ) in statuses:
        AssetStatus.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "is_final": is_final,
                "is_system": True,
                "is_active": True,
            }
        )
class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_assetstatus_is_final_assetstatus_is_system'),
    ]

    operations = [
        migrations.RunPython(seed_asset_statuses),
    ]
