# Generated by Django 6.0.2 on 2026-04-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_seed_asset_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetIncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('auto_create_maintenance', models.BooleanField(default=False)),
                ('financial_impact', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
