# Generated by Django 6.0.2 on 2026-04-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_assetincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaintenancerecord',
            name='incident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_record', to='assets.assetincident'),
        ),
    ]
