# Generated by Django 6.0.2 on 2026-04-15 16:20

from decimal import Decimal
from django.db import migrations, models


def copy_debit_credit_to_entry_side(apps, schema_editor):
    JournalLine = apps.get_model("account", "JournalLine")
    for line in JournalLine.objects.all():
        debit_amount = getattr(line, "debit_amount", Decimal("0.00")) or Decimal("0.00")
        credit_amount = getattr(line, "credit_amount", Decimal("0.00")) or Decimal("0.00")
        if credit_amount > Decimal("0.00"):
            line.entry_side = "credit"
            line.amount = credit_amount
        else:
            line.entry_side = "debit"
            line.amount = debit_amount
        line.save(update_fields=["entry_side", "amount"])


def reverse_copy_entry_side_to_debit_credit(apps, schema_editor):
    JournalLine = apps.get_model("account", "JournalLine")
    for line in JournalLine.objects.all():
        if getattr(line, "entry_side", "debit") == "credit":
            line.debit_amount = Decimal("0.00")
            line.credit_amount = getattr(line, "amount", Decimal("0.00")) or Decimal("0.00")
        else:
            line.debit_amount = getattr(line, "amount", Decimal("0.00")) or Decimal("0.00")
            line.credit_amount = Decimal("0.00")
        line.save(update_fields=["debit_amount", "credit_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_journalentry_journalline_ledgerposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='journalline',
            name='entry_side',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10),
        ),
        migrations.RunPython(copy_debit_credit_to_entry_side, reverse_copy_entry_side_to_debit_credit),
        migrations.RemoveField(
            model_name='journalline',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='debit_amount',
        ),
    ]
