# Generated by Django 6.0.2 on 2026-06-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registry', '0005_add_more_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='client_business_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_plan_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_registered_on_idx',
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='license_client_idx',
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='license_plan_idx',
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='license_is_current_idx',
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='license_expires_on_idx',
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='license_client_current_idx',
        ),
        migrations.RemoveIndex(
            model_name='licenserenewhistory',
            name='license_history_license_idx',
        ),
        migrations.RemoveIndex(
            model_name='licenserenewhistory',
            name='license_history_renewed_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='licenserenewhistory',
            name='license_history_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='loginhistory_client_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='loginhistory_logged_in_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='loginhistory_is_successful_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscription_client_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscription_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscription_interval_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscription_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantdb',
            name='tenantdb_client_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantdb',
            name='tenantdb_db_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantdb',
            name='tenantdb_status_idx',
        ),
        migrations.AddField(
            model_name='tenantdb',
            name='code',
            field=models.CharField(max_length=50, unique=True, null=True, blank=True),
        ),
    ]
