# Generated by Django 6.0.2 on 2026-03-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_nullable_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Optional name for the shift (e.g., 'Morning Shift', 'Evening Shift')", max_length=255, null=True)),
                ('code', models.CharField(blank=True, help_text="Optional code for the shift (e.g., 'MOR', 'EVE')", max_length=100, null=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('break_start_time', models.TimeField(blank=True)),
                ('break_end_time', models.TimeField(blank=True)),
                ('grace_start_time', models.TimeField(blank=True)),
                ('grace_end_time', models.TimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('break_duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeebank',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('hourly', 'Hourly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeework',
            name='work_location',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('branch', 'Branch')], max_length=20),
        ),
    ]
