# Generated by Django 6.0.2 on 2026-03-13 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_shift_alter_employee_employee_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeement_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='job_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='leave_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='job_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('vacancies', models.PositiveIntegerField(default=0, help_text='Number of vacancies for this job position')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the job position')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary for this job position', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary for this job position', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department associated with this job position', null=True, on_delete=django.db.models.deletion.RESTRICT, to='hr.department')),
                ('designation', models.ForeignKey(blank=True, help_text='Designation associated with this job position', null=True, on_delete=django.db.models.deletion.RESTRICT, to='hr.designation')),
                ('employeement_type', models.ForeignKey(blank=True, help_text='Employment type associated with this job position', null=True, on_delete=django.db.models.deletion.RESTRICT, to='hr.employeement_type')),
                ('job_category', models.ForeignKey(blank=True, help_text='Job category associated with this job position', null=True, on_delete=django.db.models.deletion.RESTRICT, to='hr.job_category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
