# Generated by Django 6.0.2 on 2026-03-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employeement_type_job_category_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='break_duration',
            field=models.PositiveIntegerField(help_text='Break duration in minutes'),
        ),
    ]
