# Generated by Django 6.0.2 on 2026-03-14 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_shift_break_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hr.job_position')),
            ],
            options={
                'ordering': ['job_position'],
            },
        ),
    ]
