# Generated by Django 6.0.2 on 2026-03-14 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_branch'),
        ('hr', '0009_job_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the applicant', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the applicant', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the applicant', max_length=20, null=True)),
                ('date_of_birth', models.DateField(help_text='Date of birth of the applicant', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender of the applicant', max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], help_text='Marital status of the applicant', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Address of the applicant', null=True)),
                ('city', models.CharField(blank=True, help_text='City of the applicant', max_length=255, null=True)),
                ('cv', models.FileField(blank=True, help_text='CV of the applicant', null=True, upload_to='applicants/cvs/')),
                ('cover_letter', models.FileField(blank=True, help_text='Cover letter of the applicant', null=True, upload_to='applicants/cover_letters/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('selected', 'Selected'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', help_text='Application status', max_length=50)),
                ('date', models.DateField(blank=True, help_text='Date of application', null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
