# Generated by Django 6.0.2 on 2026-03-17 02:02

import nepanest.modules.human_resources.models.applicant
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_approvalentity'),
        ('hr', '0011_rename_job_posting_jobposting_applicant_job_posting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='leave_type',
            new_name='ApprovalWorkflowLevel',
        ),
        migrations.RenameModel(
            old_name='job_category',
            new_name='JobCategory',
        ),
        migrations.RenameModel(
            old_name='job_position',
            new_name='JobPosition',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cover_letter',
            field=models.FileField(blank=True, help_text='Cover letter of the applicant', null=True, upload_to=nepanest.modules.human_resources.models.applicant.applicant_cover_letter_path),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, help_text='CV of the applicant', null=True, upload_to=nepanest.modules.human_resources.models.applicant.applicant_cv_path),
        ),
        migrations.CreateModel(
            name='HiringPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the hiring plan', max_length=255, unique=True)),
                ('code', models.CharField(help_text='Code of the hiring plan', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the hiring plan')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Status of the hiring plan', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(help_text='Fiscal year of the hiring plan', on_delete=django.db.models.deletion.CASCADE, to='core.fiscalyear')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='employeement_type',
            new_name='EmploymentType',
        ),
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('vacancies', models.PositiveIntegerField(default=1, help_text='Number of vacancies for the job requisition')),
                ('job_title', models.CharField(max_length=150)),
                ('job_description', models.TextField(blank=True)),
                ('job_responsibilities', models.TextField(blank=True)),
                ('required_skills', models.TextField(blank=True)),
                ('required_experience', models.CharField(blank=True, max_length=100)),
                ('education_requirement', models.TextField(blank=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('job_location', models.CharField(blank=True, max_length=150)),
                ('priority', models.CharField(max_length=20)),
                ('expected_joining_date', models.DateField(blank=True, null=True)),
                ('recruitment_reason', models.CharField(choices=[('replacement', 'Replacement'), ('new_position', 'New Position'), ('expansion', 'Expansion')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch for which the job is being requisitioned', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('department', models.ForeignKey(blank=True, help_text='Department for which the job is being requisitioned', null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.department')),
                ('designation', models.ForeignKey(blank=True, help_text='Designation for which the job is being requisitioned', null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.designation')),
                ('employment_type', models.ForeignKey(blank=True, help_text='Employment type for the job', null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employmenttype')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
