# Generated by Django 6.0.2 on 2026-03-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fiscalyear_is_current'),
        ('hr', '0023_jobpostingchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fiscalyear'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='title',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JobPostingChannelMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_url', models.URLField(blank=True, max_length=255, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(blank=True, help_text='Fiscal year', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fiscalyear')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobposting')),
                ('job_posting_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpostingchannel')),
            ],
            options={
                'db_table': 'hr_job_posting_channel_map',
            },
        ),
    ]
