# Generated by Django 6.0.2 on 2026-03-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("hr", "0035_alter_attendanceadjustment_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=255, unique=True)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("attendance", "Attendance"),
                            ("leave", "Leave"),
                            ("overtime", "Overtime"),
                            ("payroll", "Payroll"),
                            ("inventory", "Inventory"),
                            ("sales", "Sales"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        blank=True,
                        help_text="Optional event name like check_in or check_out.",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("priority", models.IntegerField(default=1)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="PolicyAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("SET_FIELD", "Set field"),
                            ("APPEND_REMARK", "Append remark"),
                            ("MARK_LATE", "Mark late"),
                            ("MARK_HALF_DAY", "Mark half day"),
                            ("SET_STATUS", "Set status"),
                        ],
                        default="SET_FIELD",
                        max_length=50,
                    ),
                ),
                (
                    "target_field",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("status", "Status"),
                            ("remarks", "Remarks"),
                            ("is_late", "Is Late"),
                            ("is_half_day", "Is Half Day"),
                        ],
                        max_length=255,
                    ),
                ),
                ("action_value", models.TextField(blank=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="hr.policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Action",
                "verbose_name_plural": "Policy Actions",
                "ordering": ["policy", "sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="PolicyCondition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("employee_id", "Employee"),
                            ("department_id", "Department"),
                            ("designation_id", "Designation"),
                            ("employee_type", "Employee Type"),
                            ("employment_status", "Employment Status"),
                            ("shift_id", "Shift"),
                            ("shift_code", "Shift Code"),
                            ("attendance_status", "Attendance Status"),
                            ("check_in_time", "Check In Time"),
                            ("check_out_time", "Check Out Time"),
                            ("is_late", "Is Late"),
                            ("is_half_day", "Is Half Day"),
                            ("weekday", "Weekday"),
                            ("overtime_date", "Overtime Date"),
                            ("overtime_start_time", "Overtime Start Time"),
                            ("overtime_end_time", "Overtime End Time"),
                            ("overtime_status", "Overtime Status"),
                            ("requested_hours", "Requested Hours"),
                            ("overtime_hours", "Overtime Hours"),
                            ("overtime_rate", "Overtime Rate"),
                            ("overtime_amount", "Overtime Amount"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("eq", "Equals"),
                            ("neq", "Not Equals"),
                            ("gt", "Greater Than"),
                            ("gte", "Greater Than or Equal"),
                            ("lt", "Less Than"),
                            ("lte", "Less Than or Equal"),
                            ("in", "In"),
                            ("not_in", "Not In"),
                            ("contains", "Contains"),
                            ("is_true", "Is True"),
                            ("is_false", "Is False"),
                            ("is_null", "Is Null"),
                            ("not_null", "Is Not Null"),
                        ],
                        default="eq",
                        max_length=255,
                    ),
                ),
                ("value", models.TextField(blank=True)),
                (
                    "logical_operator",
                    models.CharField(choices=[("AND", "AND"), ("OR", "OR")], default="AND", max_length=10),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="hr.policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Condition",
                "verbose_name_plural": "Policy Conditions",
                "ordering": ["policy", "sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="PolicyScope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to="hr.policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Scope",
                "verbose_name_plural": "Policy Scopes",
                "ordering": ["policy", "content_type", "object_id"],
                "unique_together": {("policy", "content_type", "object_id")},
            },
        ),
    ]
