# Generated by Django 6.0.2 on 2026-03-25 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_fiscalyear_is_current"),
        ("hr", "0037_attendance_is_half_day_attendance_is_late_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertimeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overtime_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("requested_hours", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="overtime_requests_approved", to=settings.AUTH_USER_MODEL)),
                ("employee", models.ForeignKey(db_column="employee_id", on_delete=django.db.models.deletion.CASCADE, related_name="overtime_requests", to="hr.employee")),
                ("fiscal_year", models.ForeignKey(blank=True, help_text="Fiscal year", null=True, on_delete=django.db.models.deletion.CASCADE, to="core.fiscalyear")),
                ("requested_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="overtime_requests_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-overtime_date", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OvertimeRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overtime_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("overtime_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("overtime_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("overtime_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee", models.ForeignKey(db_column="employee_id", on_delete=django.db.models.deletion.CASCADE, related_name="overtime_records", to="hr.employee")),
                ("fiscal_year", models.ForeignKey(blank=True, help_text="Fiscal year", null=True, on_delete=django.db.models.deletion.CASCADE, to="core.fiscalyear")),
                ("request", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="overtime_record", to="hr.overtimerequest")),
            ],
            options={
                "ordering": ["-overtime_date", "-created_at", "-id"],
            },
        ),
    ]
