# Generated by Django 6.0.2 on 2026-03-26 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0044_alter_leaveapproval_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='leaveapproval',
            constraint=models.UniqueConstraint(fields=('leave_request', 'level'), name='unique_leave_approval_request_level'),
        ),
        migrations.AddConstraint(
            model_name='leaveapproval',
            constraint=models.UniqueConstraint(fields=('leave_request', 'approver', 'level'), name='unique_leave_approval_request_approver_level'),
        ),
    ]
