# Generated by Django 6.0.2 on 2026-03-27 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fiscalyear_is_current'),
        ('hr', '0046_alter_hire_status_alter_hiringplan_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer Contribution'), ('information', 'Information')], max_length=30)),
                ('value_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage'), ('formula', 'Formula')], max_length=30)),
                ('formula_expression', models.TextField(blank=True)),
                ('tax_treatment', models.CharField(choices=[('taxable', 'Taxable'), ('non_taxable', 'Non Taxable'), ('tax_exempt', 'Tax Exempt')], default='taxable', max_length=30)),
                ('affects_gross', models.BooleanField(default=True)),
                ('affects_net', models.BooleanField(default=True)),
                ('is_statutory', models.BooleanField(default=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['name', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Biweekly'), ('weekly', 'Weekly')], default='monthly', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_assignments_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='salary_assignments', to='hr.employee')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='hr.salarystructure')),
            ],
            options={
                'ordering': ['employee__employee_id', '-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('default_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('formula_expression', models.TextField(blank=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rounding_rule', models.CharField(choices=[('round_2', 'Round 2 Decimals'), ('round_0', 'Round Whole Number'), ('ceil', 'Ceil'), ('floor', 'Floor')], default='round_2', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_editable', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage_of_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='percentage_based_structure_components', to='hr.salarycomponent')),
                ('salary_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structure_components', to='hr.salarycomponent')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hr.salarystructure')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeComponentOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('override_formula', models.TextField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_salary_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_overrides', to='hr.employeesalaryassignment')),
                ('salary_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_overrides', to='hr.salarycomponent')),
            ],
            options={
                'ordering': ['salary_component__sequence', 'salary_component__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('employee_salary_assignment', 'salary_component'), name='unique_employee_salary_override_component')],
            },
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'name', 'effective_from'), name='unique_salary_structure_scope_name_effective_from'),
        ),
        migrations.AddConstraint(
            model_name='salarystructurecomponent',
            constraint=models.UniqueConstraint(fields=('salary_structure', 'salary_component'), name='unique_salary_structure_component'),
        ),
    ]
