# Generated by Django 6.0.2 on 2026-03-27 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fiscalyear_is_current'),
        ('hr', '0047_salarycomponent_salarystructure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('payroll_year', models.PositiveIntegerField()),
                ('payroll_month', models.PositiveSmallIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payroll_year', '-payroll_month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRunEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_structure_name', models.CharField(blank=True, max_length=120)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('employer_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=20)),
                ('calculation_summary', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run_rows', to='hr.employee')),
                ('employee_salary_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run_rows', to='hr.employeesalaryassignment')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hr.payrollrun')),
            ],
            options={
                'ordering': ['employee__employee_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRunComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('structure', 'Structure'), ('override', 'Override'), ('adjustment', 'Adjustment'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('overtime', 'Overtime'), ('tax', 'Tax'), ('statutory', 'Statutory')], default='structure', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('calculation_trace', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_run_components', to='hr.salarycomponent')),
                ('payroll_run_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hr.payrollrunemployee')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'payroll_year', 'payroll_month'), name='unique_payroll_run_scope_period'),
        ),
        migrations.AddConstraint(
            model_name='payrollrunemployee',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='unique_payroll_run_employee'),
        ),
        migrations.AddConstraint(
            model_name='payrollruncomponent',
            constraint=models.UniqueConstraint(fields=('payroll_run_employee', 'salary_component'), name='unique_payroll_run_employee_component'),
        ),
    ]
