# Generated by Django 6.0.2 on 2026-04-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_locationtype_location'),
        ('hr', '0058_teamrole_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_organization_records', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='team',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_branch_records', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_organization_records', to='core.organization'),
        ),
    ]
