# Generated by Django 6.0.2 on 2026-04-08 15:44

from django.db import migrations


def seed_team_roles(apps, schema_editor):
    TeamRole = apps.get_model("hr", "TeamRole")

    roles = [
        {"name": "Team Leader", "code": "TEAM_LEADER", "level": 1},
        {"name": "Manager", "code": "MANAGER", "level": 2},
        {"name": "Senior Member", "code": "SENIOR_MEMBER", "level": 3},
        {"name": "Member", "code": "MEMBER", "level": 4},
        {"name": "Intern / Trainee", "code": "INTERN", "level": 5},
    ]

    for role in roles:
        TeamRole.objects.get_or_create(
            code=role["code"],
            defaults={
                "name": role["name"],
                "level": role["level"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0059_teammember_organization_alter_team_branch_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_team_roles),
    ]
