# Generated by Django 6.0.2 on 2026-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={},
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='database_alias',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_host',
            field=models.CharField(default='127.0.0.1', max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_name',
            field=models.CharField(default='default_db', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_password',
            field=models.CharField(default='Password', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_port',
            field=models.CharField(default='3306', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='db_user',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('trial', 'Trial')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='tenant',
            table='platform_tenants',
        ),
    ]
