# Generated manually on 2026-04-15

from django.db import migrations


COMMON_VOUCHER_TYPES = [
    {
        "code": "PAY",
        "name": "Payment",
        "category": "cash",
        "nature": "credit_based",
        "affects_cash": True,
        "affects_bank": False,
        "auto_numbering": True,
        "prefix": "PAY-",
        "last_number": 0,
        "requires_reference": True,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "Cash payment voucher.",
    },
    {
        "code": "BPV",
        "name": "Bank Payment",
        "category": "bank",
        "nature": "credit_based",
        "affects_cash": False,
        "affects_bank": True,
        "auto_numbering": True,
        "prefix": "BPV-",
        "last_number": 0,
        "requires_reference": True,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "Bank payment voucher.",
    },
    {
        "code": "REC",
        "name": "Receipt",
        "category": "cash",
        "nature": "debit_based",
        "affects_cash": True,
        "affects_bank": False,
        "auto_numbering": True,
        "prefix": "REC-",
        "last_number": 0,
        "requires_reference": True,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "Cash receipt voucher.",
    },
    {
        "code": "BRV",
        "name": "Bank Receipt",
        "category": "bank",
        "nature": "debit_based",
        "affects_cash": False,
        "affects_bank": True,
        "auto_numbering": True,
        "prefix": "BRV-",
        "last_number": 0,
        "requires_reference": True,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "Bank receipt voucher.",
    },
    {
        "code": "JV",
        "name": "Journal",
        "category": "journal",
        "nature": "both",
        "affects_cash": False,
        "affects_bank": False,
        "auto_numbering": True,
        "prefix": "JRN-",
        "last_number": 0,
        "requires_reference": False,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "General journal voucher.",
    },
    {
        "code": "CON",
        "name": "Contra",
        "category": "bank",
        "nature": "both",
        "affects_cash": True,
        "affects_bank": True,
        "auto_numbering": True,
        "prefix": "CON-",
        "last_number": 0,
        "requires_reference": False,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "Contra voucher for cash and bank transfers.",
    },
    {
        "code": "SAL",
        "name": "Sales",
        "category": "sales",
        "nature": "credit_based",
        "affects_cash": False,
        "affects_bank": False,
        "auto_numbering": True,
        "prefix": "SAL-",
        "last_number": 0,
        "requires_reference": True,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "Sales voucher.",
    },
    {
        "code": "SRN",
        "name": "Sales Return",
        "category": "sales",
        "nature": "debit_based",
        "affects_cash": False,
        "affects_bank": False,
        "auto_numbering": True,
        "prefix": "SRN-",
        "last_number": 0,
        "requires_reference": True,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "Sales return voucher.",
    },
    {
        "code": "PUR",
        "name": "Purchase",
        "category": "purchase",
        "nature": "debit_based",
        "affects_cash": False,
        "affects_bank": False,
        "auto_numbering": True,
        "prefix": "PUR-",
        "last_number": 0,
        "requires_reference": True,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "Purchase voucher.",
    },
    {
        "code": "PRN",
        "name": "Purchase Return",
        "category": "purchase",
        "nature": "credit_based",
        "affects_cash": False,
        "affects_bank": False,
        "auto_numbering": True,
        "prefix": "PRN-",
        "last_number": 0,
        "requires_reference": True,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "Purchase return voucher.",
    },
    {
        "code": "CRN",
        "name": "Credit Note",
        "category": "adjustment",
        "nature": "credit_based",
        "affects_cash": False,
        "affects_bank": False,
        "auto_numbering": True,
        "prefix": "CRN-",
        "last_number": 0,
        "requires_reference": True,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "Credit note voucher.",
    },
    {
        "code": "DBN",
        "name": "Debit Note",
        "category": "adjustment",
        "nature": "debit_based",
        "affects_cash": False,
        "affects_bank": False,
        "auto_numbering": True,
        "prefix": "DBN-",
        "last_number": 0,
        "requires_reference": True,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "Debit note voucher.",
    },
    {
        "code": "ADJ",
        "name": "Adjustment",
        "category": "adjustment",
        "nature": "both",
        "affects_cash": False,
        "affects_bank": False,
        "auto_numbering": True,
        "prefix": "ADJ-",
        "last_number": 0,
        "requires_reference": False,
        "requires_approval": False,
        "allow_negative": False,
        "is_system_generated": False,
        "is_active": True,
        "description": "Manual adjustment voucher.",
    },
]


def seed_common_voucher_types(apps, schema_editor):
    VoucherType = apps.get_model("account", "VoucherType")
    for item in COMMON_VOUCHER_TYPES:
        code = item["code"]
        defaults = dict(item)
        defaults.pop("code", None)
        VoucherType.objects.update_or_create(code=code, defaults=defaults)


def unseed_common_voucher_types(apps, schema_editor):
    VoucherType = apps.get_model("account", "VoucherType")
    VoucherType.objects.filter(code__in=[item["code"] for item in COMMON_VOUCHER_TYPES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_vouchertype_accounting_fields"),
    ]

    operations = [
        migrations.RunPython(seed_common_voucher_types, unseed_common_voucher_types),
    ]
